### PR TITLE
Migrate jquery away

### PR DESCRIPTION
**Pull request by marcbachmann**
### Changelog
- 🎁 Get rid of any jquery reference in the source code

The tests are still using some functions

### CODE REVIEW

**Comment by jenstroeger** [comment]
The changes in this PR add to PR https://github.com/livingdocsIO/editable.js/pull/220?

**Comment by marcbachmann** [comment]
We can change the base after the other one is merged. I just wanted to build on it.

**Comment by marcbachmann** [comment]
There are still some query events to replace in https://github.com/livingdocsIO/editable.js/blame/master/src/dispatcher.js#L27. I think the rest should be fine.

**Review by peyerluk — APPROVED** [review]

**Comment by VFertak** [comment]
What an achievement!! Congrats guys!!!🍾

**Comment by jenstroeger** [comment]
Agreed, thank you @marcbachmann!

**Comment by marcbachmann** [comment]
Finished and the module is now named `editable.js` on npm.

**Comment by marcbachmann** [comment]
> "npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/editable.js - Package name too similar to existing packages; try renaming your package to '@livingdocs-bot/editable.js' and publishing with 'npm publish --access=public' instead\n" +

Ok, I'll have to rename again. @peyerluk should we use `@livingdocs/editable.js`?

**Comment by marcbachmann** [comment]
@jenstroeger the module is now published as https://www.npmjs.com/package/@livingdocs/editable.js

**Pull request merged**
