### PR TITLE
feat(selection): Add isWrappable() helper function.

### PR DESCRIPTION
**Pull request by jenstroeger**

### CODE REVIEW

**Comment by peyerluk** [comment]
Out of curiosity: what use case do you need this method for?

**Comment by jenstroeger** [comment]
In the `"selection"` event handler I check whether the given selection can be wrapped at all, and only if it can be wrapped does a little toolbar pop open.

**Comment by jenstroeger** [comment]
Any chance we can merge this one, too, please? 😇

**Comment by jenstroeger** [comment]
@peyerluk @marcbachmann I don’t know why this PR’s checks are stuck, can you please check? It’d be great to merge.

**Comment by marcbachmann** [comment]
It's just the eslint reporting that doesn't work for pull requests as the token doesn't get injected for security reasons.

**Pull request merged**
